<?php

namespace app\misc;

class PokedexData
{
	const EXPERIENCE_SLOW        = 0;
	const EXPERIENCE_MEDIUM_SLOW = 1;
	const EXPERIENCE_MEDIUM_FAST = 2;
	const EXPERIENCE_FAST        = 3;
	const EXPERIENCE_FLUCTUATING = 4;
	const EXPERIENCE_ERRATIC     = 5;

	protected static $pokemon = array(
		1   => array('name' => 'Bulbasaur',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		2   => array('name' => 'Ivysaur',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		3   => array('name' => 'Venusaur',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		4   => array('name' => 'Charmander',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		5   => array('name' => 'Charmeleon',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		6   => array('name' => 'Charizard',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		7   => array('name' => 'Squirtle',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		8   => array('name' => 'Wartortle',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		9   => array('name' => 'Blastoise',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		10  => array('name' => 'Caterpie',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		11  => array('name' => 'Metapod',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		12  => array('name' => 'Butterfree',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		13  => array('name' => 'Weedle',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		14  => array('name' => 'Kakuna',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		15  => array('name' => 'Beedrill',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		16  => array('name' => 'Pidgey',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		17  => array('name' => 'Pidgeotto',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		18  => array('name' => 'Pidgeot',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		19  => array('name' => 'Rattata',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		20  => array('name' => 'Raticate',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		21  => array('name' => 'Spearow',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		22  => array('name' => 'Fearow',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		23  => array('name' => 'Ekans',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		24  => array('name' => 'Arbok',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		25  => array('name' => 'Pikachu',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		26  => array('name' => 'Raichu',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		27  => array('name' => 'Sandshrew',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		28  => array('name' => 'Sandslash',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		29  => array('name' => 'Nidoran♀',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		30  => array('name' => 'Nidorina',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		31  => array('name' => 'Nidoqueen',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		32  => array('name' => 'Nidoran♂',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		33  => array('name' => 'Nidorino',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		34  => array('name' => 'Nidoking',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		35  => array('name' => 'Clefairy',    'experience' => self::EXPERIENCE_FAST),
		36  => array('name' => 'Clefable',    'experience' => self::EXPERIENCE_FAST),
		37  => array('name' => 'Vulpix',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		38  => array('name' => 'Ninetales',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		39  => array('name' => 'Jigglypuff',  'experience' => self::EXPERIENCE_FAST),
		40  => array('name' => 'Wigglytuff',  'experience' => self::EXPERIENCE_FAST),
		41  => array('name' => 'Zubat',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		42  => array('name' => 'Golbat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		43  => array('name' => 'Oddish',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		44  => array('name' => 'Gloom',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		45  => array('name' => 'Vileplume',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		46  => array('name' => 'Paras',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		47  => array('name' => 'Parasect',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		48  => array('name' => 'Venonat',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		49  => array('name' => 'Venomoth',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		50  => array('name' => 'Diglett',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		51  => array('name' => 'Dugtrio',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		52  => array('name' => 'Meowth',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		53  => array('name' => 'Persian',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		54  => array('name' => 'Psyduck',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		55  => array('name' => 'Golduck',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		56  => array('name' => 'Mankey',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		57  => array('name' => 'Primeape',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		58  => array('name' => 'Growlithe',   'experience' => self::EXPERIENCE_SLOW),
		59  => array('name' => 'Arcanine',    'experience' => self::EXPERIENCE_SLOW),
		60  => array('name' => 'Poliwag',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		61  => array('name' => 'Poliwhirl',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		62  => array('name' => 'Poliwrath',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		63  => array('name' => 'Abra',        'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		64  => array('name' => 'Kadabra',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		65  => array('name' => 'Alakazam',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		66  => array('name' => 'Machop',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		67  => array('name' => 'Machoke',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		68  => array('name' => 'Machamp',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		69  => array('name' => 'Bellsprout',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		70  => array('name' => 'Weepinbell',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		71  => array('name' => 'Victreebel',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		72  => array('name' => 'Tentacool',   'experience' => self::EXPERIENCE_SLOW),
		73  => array('name' => 'Tentacruel',  'experience' => self::EXPERIENCE_SLOW),
		74  => array('name' => 'Geodude',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		75  => array('name' => 'Graveler',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		76  => array('name' => 'Golem',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		77  => array('name' => 'Ponyta',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		78  => array('name' => 'Rapidash',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		79  => array('name' => 'Slowpoke',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		80  => array('name' => 'Slowbro',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		81  => array('name' => 'Magnemite',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		82  => array('name' => 'Magneton',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		83  => array('name' => 'Farfetch\'d', 'experience' => self::EXPERIENCE_MEDIUM_FAST),
		84  => array('name' => 'Doduo',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		85  => array('name' => 'Dodrio',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		86  => array('name' => 'Seel',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		87  => array('name' => 'Dewgong',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		88  => array('name' => 'Grimer',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		89  => array('name' => 'Muk',         'experience' => self::EXPERIENCE_MEDIUM_FAST),
		90  => array('name' => 'Shellder',    'experience' => self::EXPERIENCE_SLOW),
		91  => array('name' => 'Cloyster',    'experience' => self::EXPERIENCE_SLOW),
		92  => array('name' => 'Gastly',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		93  => array('name' => 'Haunter',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		94  => array('name' => 'Gengar',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		95  => array('name' => 'Onix',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		96  => array('name' => 'Drowzee',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		97  => array('name' => 'Hypno',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		98  => array('name' => 'Krabby',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		99  => array('name' => 'Kingler',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		100 => array('name' => 'Voltorb',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		101 => array('name' => 'Electrode',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		102 => array('name' => 'Exeggcute',   'experience' => self::EXPERIENCE_SLOW),
		103 => array('name' => 'Exeggutor',   'experience' => self::EXPERIENCE_SLOW),
		104 => array('name' => 'Cubone',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		105 => array('name' => 'Marowak',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		106 => array('name' => 'Hitmonlee',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		107 => array('name' => 'Hitmonchan',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		108 => array('name' => 'Lickitung',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		109 => array('name' => 'Koffing',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		110 => array('name' => 'Weezing',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		111 => array('name' => 'Rhyhorn',     'experience' => self::EXPERIENCE_SLOW),
		112 => array('name' => 'Rhydon',      'experience' => self::EXPERIENCE_SLOW),
		113 => array('name' => 'Chansey',     'experience' => self::EXPERIENCE_FAST),
		114 => array('name' => 'Tangela',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		115 => array('name' => 'Kangaskhan',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		116 => array('name' => 'Horsea',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		117 => array('name' => 'Seadra',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		118 => array('name' => 'Goldeen',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		119 => array('name' => 'Seaking',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		120 => array('name' => 'Staryu',      'experience' => self::EXPERIENCE_SLOW),
		121 => array('name' => 'Starmie',     'experience' => self::EXPERIENCE_SLOW),
		122 => array('name' => 'Mr. Mime',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		123 => array('name' => 'Scyther',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		124 => array('name' => 'Jynx',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		125 => array('name' => 'Electabuzz',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		126 => array('name' => 'Magmar',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		127 => array('name' => 'Pinsir',      'experience' => self::EXPERIENCE_SLOW),
		128 => array('name' => 'Tauros',      'experience' => self::EXPERIENCE_SLOW),
		129 => array('name' => 'Magikarp',    'experience' => self::EXPERIENCE_SLOW),
		130 => array('name' => 'Gyarados',    'experience' => self::EXPERIENCE_SLOW),
		131 => array('name' => 'Lapras',      'experience' => self::EXPERIENCE_SLOW),
		132 => array('name' => 'Ditto',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		133 => array('name' => 'Eevee',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		134 => array('name' => 'Vaporeon',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		135 => array('name' => 'Jolteon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		136 => array('name' => 'Flareon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		137 => array('name' => 'Porygon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		138 => array('name' => 'Omanyte',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		139 => array('name' => 'Omastar',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		140 => array('name' => 'Kabuto',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		141 => array('name' => 'Kabutops',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		142 => array('name' => 'Aerodactyl',  'experience' => self::EXPERIENCE_SLOW),
		143 => array('name' => 'Snorlax',     'experience' => self::EXPERIENCE_SLOW),
		144 => array('name' => 'Articuno',    'experience' => self::EXPERIENCE_SLOW),
		145 => array('name' => 'Zapdos',      'experience' => self::EXPERIENCE_SLOW),
		146 => array('name' => 'Moltres',     'experience' => self::EXPERIENCE_SLOW),
		147 => array('name' => 'Dratini',     'experience' => self::EXPERIENCE_SLOW),
		148 => array('name' => 'Dragonair',   'experience' => self::EXPERIENCE_SLOW),
		149 => array('name' => 'Dragonite',   'experience' => self::EXPERIENCE_SLOW),
		150 => array('name' => 'Mewtwo',      'experience' => self::EXPERIENCE_SLOW),
		151 => array('name' => 'Mew',         'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		152 => array('name' => 'Chikorita',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		153 => array('name' => 'Bayleef',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		154 => array('name' => 'Meganium',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		155 => array('name' => 'Cyndaquil',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		156 => array('name' => 'Quilava',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		157 => array('name' => 'Typhlosion',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		158 => array('name' => 'Totodile',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		159 => array('name' => 'Croconaw',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		160 => array('name' => 'Feraligatr',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		161 => array('name' => 'Sentret',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		162 => array('name' => 'Furret',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		163 => array('name' => 'Hoothoot',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		164 => array('name' => 'Noctowl',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		165 => array('name' => 'Ledyba',      'experience' => self::EXPERIENCE_FAST),
		166 => array('name' => 'Ledian',      'experience' => self::EXPERIENCE_FAST),
		167 => array('name' => 'Spinarak',    'experience' => self::EXPERIENCE_FAST),
		168 => array('name' => 'Ariados',     'experience' => self::EXPERIENCE_FAST),
		169 => array('name' => 'Crobat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		170 => array('name' => 'Chinchou',    'experience' => self::EXPERIENCE_SLOW),
		171 => array('name' => 'Lanturn',     'experience' => self::EXPERIENCE_SLOW),
		172 => array('name' => 'Pichu',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		173 => array('name' => 'Cleffa',      'experience' => self::EXPERIENCE_FAST),
		174 => array('name' => 'Igglybuff',   'experience' => self::EXPERIENCE_FAST),
		175 => array('name' => 'Togepi',      'experience' => self::EXPERIENCE_FAST),
		176 => array('name' => 'Togetic',     'experience' => self::EXPERIENCE_FAST),
		177 => array('name' => 'Natu',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		178 => array('name' => 'Xatu',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		179 => array('name' => 'Mareep',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		180 => array('name' => 'Flaaffy',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		181 => array('name' => 'Ampharos',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		182 => array('name' => 'Bellossom',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		183 => array('name' => 'Marill',      'experience' => self::EXPERIENCE_FAST),
		184 => array('name' => 'Azumarill',   'experience' => self::EXPERIENCE_FAST),
		185 => array('name' => 'Sudowoodo',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		186 => array('name' => 'Politoed',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		187 => array('name' => 'Hoppip',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		188 => array('name' => 'Skiploom',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		189 => array('name' => 'Jumpluff',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		190 => array('name' => 'Aipom',       'experience' => self::EXPERIENCE_FAST),
		191 => array('name' => 'Sunkern',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		192 => array('name' => 'Sunflora',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		193 => array('name' => 'Yanma',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		194 => array('name' => 'Wooper',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		195 => array('name' => 'Quagsire',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		196 => array('name' => 'Espeon',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		197 => array('name' => 'Umbreon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		198 => array('name' => 'Murkrow',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		199 => array('name' => 'Slowking',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		200 => array('name' => 'Misdreavus',  'experience' => self::EXPERIENCE_FAST),
		201 => array('name' => 'Unown',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		202 => array('name' => 'Wobbuffet',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		203 => array('name' => 'Girafarig',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		204 => array('name' => 'Pineco',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		205 => array('name' => 'Forretress',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		206 => array('name' => 'Dunsparce',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		207 => array('name' => 'Gligar',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		208 => array('name' => 'Steelix',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		209 => array('name' => 'Snubbull',    'experience' => self::EXPERIENCE_FAST),
		210 => array('name' => 'Granbull',    'experience' => self::EXPERIENCE_FAST),
		211 => array('name' => 'Qwilfish',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		212 => array('name' => 'Scizor',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		213 => array('name' => 'Shuckle',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		214 => array('name' => 'Heracross',   'experience' => self::EXPERIENCE_SLOW),
		215 => array('name' => 'Sneasel',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		216 => array('name' => 'Teddiursa',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		217 => array('name' => 'Ursaring',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		218 => array('name' => 'Slugma',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		219 => array('name' => 'Magcargo',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		220 => array('name' => 'Swinub',      'experience' => self::EXPERIENCE_SLOW),
		221 => array('name' => 'Piloswine',   'experience' => self::EXPERIENCE_SLOW),
		222 => array('name' => 'Corsola',     'experience' => self::EXPERIENCE_FAST),
		223 => array('name' => 'Remoraid',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		224 => array('name' => 'Octillery',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		225 => array('name' => 'Delibird',    'experience' => self::EXPERIENCE_FAST),
		226 => array('name' => 'Mantine',     'experience' => self::EXPERIENCE_SLOW),
		227 => array('name' => 'Skarmory',    'experience' => self::EXPERIENCE_SLOW),
		228 => array('name' => 'Houndour',    'experience' => self::EXPERIENCE_SLOW),
		229 => array('name' => 'Houndoom',    'experience' => self::EXPERIENCE_SLOW),
		230 => array('name' => 'Kingdra',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		231 => array('name' => 'Phanpy',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		232 => array('name' => 'Donphan',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		233 => array('name' => 'Porygon2',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		234 => array('name' => 'Stantler',    'experience' => self::EXPERIENCE_SLOW),
		235 => array('name' => 'Smeargle',    'experience' => self::EXPERIENCE_FAST),
		236 => array('name' => 'Tyrogue',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		237 => array('name' => 'Hitmontop',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		238 => array('name' => 'Smoochum',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		239 => array('name' => 'Elekid',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		240 => array('name' => 'Magby',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		241 => array('name' => 'Miltank',     'experience' => self::EXPERIENCE_SLOW),
		242 => array('name' => 'Blissey',     'experience' => self::EXPERIENCE_FAST),
		243 => array('name' => 'Raikou',      'experience' => self::EXPERIENCE_SLOW),
		244 => array('name' => 'Entei',       'experience' => self::EXPERIENCE_SLOW),
		245 => array('name' => 'Suicune',     'experience' => self::EXPERIENCE_SLOW),
		246 => array('name' => 'Larvitar',    'experience' => self::EXPERIENCE_SLOW),
		247 => array('name' => 'Pupitar',     'experience' => self::EXPERIENCE_SLOW),
		248 => array('name' => 'Tyranitar',   'experience' => self::EXPERIENCE_SLOW),
		249 => array('name' => 'Lugia',       'experience' => self::EXPERIENCE_SLOW),
		250 => array('name' => 'Ho-Oh',       'experience' => self::EXPERIENCE_SLOW),
		251 => array('name' => 'Celebi',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		252 => array('name' => 'Treecko',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		253 => array('name' => 'Grovyle',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		254 => array('name' => 'Sceptile',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		255 => array('name' => 'Torchic',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		256 => array('name' => 'Combusken',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		257 => array('name' => 'Blaziken',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		258 => array('name' => 'Mudkip',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		259 => array('name' => 'Marshtomp',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		260 => array('name' => 'Swampert',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		261 => array('name' => 'Poochyena',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		262 => array('name' => 'Mightyena',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		263 => array('name' => 'Zigzagoon',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		264 => array('name' => 'Linoone',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		265 => array('name' => 'Wurmple',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		266 => array('name' => 'Silcoon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		267 => array('name' => 'Beautifly',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		268 => array('name' => 'Cascoon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		269 => array('name' => 'Dustox',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		270 => array('name' => 'Lotad',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		271 => array('name' => 'Lombre',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		272 => array('name' => 'Ludicolo',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		273 => array('name' => 'Seedot',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		274 => array('name' => 'Nuzleaf',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		275 => array('name' => 'Shiftry',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		276 => array('name' => 'Taillow',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		277 => array('name' => 'Swellow',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		278 => array('name' => 'Wingull',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		279 => array('name' => 'Pelipper',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		280 => array('name' => 'Ralts',       'experience' => self::EXPERIENCE_SLOW),
		281 => array('name' => 'Kirlia',      'experience' => self::EXPERIENCE_SLOW),
		282 => array('name' => 'Gardevoir',   'experience' => self::EXPERIENCE_SLOW),
		283 => array('name' => 'Surskit',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		284 => array('name' => 'Masquerain',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		285 => array('name' => 'Shroomish',   'experience' => self::EXPERIENCE_FLUCTUATING),
		286 => array('name' => 'Breloom',     'experience' => self::EXPERIENCE_FLUCTUATING),
		287 => array('name' => 'Slakoth',     'experience' => self::EXPERIENCE_SLOW),
		288 => array('name' => 'Vigoroth',    'experience' => self::EXPERIENCE_SLOW),
		289 => array('name' => 'Slaking',     'experience' => self::EXPERIENCE_SLOW),
		290 => array('name' => 'Nincada',     'experience' => self::EXPERIENCE_ERRATIC),
		291 => array('name' => 'Ninjask',     'experience' => self::EXPERIENCE_ERRATIC),
		292 => array('name' => 'Shedinja',    'experience' => self::EXPERIENCE_ERRATIC),
		293 => array('name' => 'Whismur',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		294 => array('name' => 'Loudred',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		295 => array('name' => 'Exploud',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		296 => array('name' => 'Makuhita',    'experience' => self::EXPERIENCE_FLUCTUATING),
		297 => array('name' => 'Hariyama',    'experience' => self::EXPERIENCE_FLUCTUATING),
		298 => array('name' => 'Azurill',     'experience' => self::EXPERIENCE_FAST),
		299 => array('name' => 'Nosepass',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		300 => array('name' => 'Skitty',      'experience' => self::EXPERIENCE_FAST),
		301 => array('name' => 'Delcatty',    'experience' => self::EXPERIENCE_FAST),
		302 => array('name' => 'Sableye',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		303 => array('name' => 'Mawile',      'experience' => self::EXPERIENCE_FAST),
		304 => array('name' => 'Aron',        'experience' => self::EXPERIENCE_SLOW),
		305 => array('name' => 'Lairon',      'experience' => self::EXPERIENCE_SLOW),
		306 => array('name' => 'Aggron',      'experience' => self::EXPERIENCE_SLOW),
		307 => array('name' => 'Meditite',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		308 => array('name' => 'Medicham',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		309 => array('name' => 'Electrike',   'experience' => self::EXPERIENCE_SLOW),
		310 => array('name' => 'Manectric',   'experience' => self::EXPERIENCE_SLOW),
		311 => array('name' => 'Plusle',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		312 => array('name' => 'Minun',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		313 => array('name' => 'Volbeat',     'experience' => self::EXPERIENCE_ERRATIC),
		314 => array('name' => 'Illumise',    'experience' => self::EXPERIENCE_FLUCTUATING),
		315 => array('name' => 'Roselia',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		316 => array('name' => 'Gulpin',      'experience' => self::EXPERIENCE_FLUCTUATING),
		317 => array('name' => 'Swalot',      'experience' => self::EXPERIENCE_FLUCTUATING),
		318 => array('name' => 'Carvanha',    'experience' => self::EXPERIENCE_SLOW),
		319 => array('name' => 'Sharpedo',    'experience' => self::EXPERIENCE_SLOW),
		320 => array('name' => 'Wailmer',     'experience' => self::EXPERIENCE_FLUCTUATING),
		321 => array('name' => 'Wailord',     'experience' => self::EXPERIENCE_FLUCTUATING),
		322 => array('name' => 'Numel',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		323 => array('name' => 'Camerupt',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		324 => array('name' => 'Torkoal',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		325 => array('name' => 'Spoink',      'experience' => self::EXPERIENCE_FAST),
		326 => array('name' => 'Grumpig',     'experience' => self::EXPERIENCE_FAST),
		327 => array('name' => 'Spinda',      'experience' => self::EXPERIENCE_FAST),
		328 => array('name' => 'Trapinch',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		329 => array('name' => 'Vibrava',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		330 => array('name' => 'Flygon',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		331 => array('name' => 'Cacnea',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		332 => array('name' => 'Cacturne',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		333 => array('name' => 'Swablu',      'experience' => self::EXPERIENCE_ERRATIC),
		334 => array('name' => 'Altaria',     'experience' => self::EXPERIENCE_ERRATIC),
		335 => array('name' => 'Zangoose',    'experience' => self::EXPERIENCE_ERRATIC),
		336 => array('name' => 'Seviper',     'experience' => self::EXPERIENCE_FLUCTUATING),
		337 => array('name' => 'Lunatone',    'experience' => self::EXPERIENCE_FAST),
		338 => array('name' => 'Solrock',     'experience' => self::EXPERIENCE_FAST),
		339 => array('name' => 'Barboach',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		340 => array('name' => 'Whiscash',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		341 => array('name' => 'Corphish',    'experience' => self::EXPERIENCE_FLUCTUATING),
		342 => array('name' => 'Crawdaunt',   'experience' => self::EXPERIENCE_FLUCTUATING),
		343 => array('name' => 'Baltoy',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		344 => array('name' => 'Claydol',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		345 => array('name' => 'Lileep',      'experience' => self::EXPERIENCE_ERRATIC),
		346 => array('name' => 'Cradily',     'experience' => self::EXPERIENCE_ERRATIC),
		347 => array('name' => 'Anorith',     'experience' => self::EXPERIENCE_ERRATIC),
		348 => array('name' => 'Armaldo',     'experience' => self::EXPERIENCE_ERRATIC),
		349 => array('name' => 'Feebas',      'experience' => self::EXPERIENCE_ERRATIC),
		350 => array('name' => 'Milotic',     'experience' => self::EXPERIENCE_ERRATIC),
		351 => array('name' => 'Castform',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		352 => array('name' => 'Kecleon',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		353 => array('name' => 'Shuppet',     'experience' => self::EXPERIENCE_FAST),
		354 => array('name' => 'Banette',     'experience' => self::EXPERIENCE_FAST),
		355 => array('name' => 'Duskull',     'experience' => self::EXPERIENCE_FAST),
		356 => array('name' => 'Dusclops',    'experience' => self::EXPERIENCE_FAST),
		357 => array('name' => 'Tropius',     'experience' => self::EXPERIENCE_SLOW),
		358 => array('name' => 'Chimecho',    'experience' => self::EXPERIENCE_FAST),
		359 => array('name' => 'Absol',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		360 => array('name' => 'Wynaut',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		361 => array('name' => 'Snorunt',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		362 => array('name' => 'Glalie',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		363 => array('name' => 'Spheal',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		364 => array('name' => 'Sealeo',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		365 => array('name' => 'Walrein',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		366 => array('name' => 'Clamperl',    'experience' => self::EXPERIENCE_ERRATIC),
		367 => array('name' => 'Huntail',     'experience' => self::EXPERIENCE_ERRATIC),
		368 => array('name' => 'Gorebyss',    'experience' => self::EXPERIENCE_ERRATIC),
		369 => array('name' => 'Relicanth',   'experience' => self::EXPERIENCE_SLOW),
		370 => array('name' => 'Luvdisc',     'experience' => self::EXPERIENCE_FAST),
		371 => array('name' => 'Bagon',       'experience' => self::EXPERIENCE_SLOW),
		372 => array('name' => 'Shelgon',     'experience' => self::EXPERIENCE_SLOW),
		373 => array('name' => 'Salamence',   'experience' => self::EXPERIENCE_SLOW),
		374 => array('name' => 'Beldum',      'experience' => self::EXPERIENCE_SLOW),
		375 => array('name' => 'Metang',      'experience' => self::EXPERIENCE_SLOW),
		376 => array('name' => 'Metagross',   'experience' => self::EXPERIENCE_SLOW),
		377 => array('name' => 'Regirock',    'experience' => self::EXPERIENCE_SLOW),
		378 => array('name' => 'Regice',      'experience' => self::EXPERIENCE_SLOW),
		379 => array('name' => 'Registeel',   'experience' => self::EXPERIENCE_SLOW),
		380 => array('name' => 'Latias',      'experience' => self::EXPERIENCE_SLOW),
		381 => array('name' => 'Latios',      'experience' => self::EXPERIENCE_SLOW),
		382 => array('name' => 'Kyogre',      'experience' => self::EXPERIENCE_SLOW),
		383 => array('name' => 'Groudon',     'experience' => self::EXPERIENCE_SLOW),
		384 => array('name' => 'Rayquaza',    'experience' => self::EXPERIENCE_SLOW),
		385 => array('name' => 'Jirachi',     'experience' => self::EXPERIENCE_SLOW),
		386 => array('name' => 'Deoxys',      'experience' => self::EXPERIENCE_SLOW),
		387 => array('name' => 'Turtwig',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		388 => array('name' => 'Grotle',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		389 => array('name' => 'Torterra',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		390 => array('name' => 'Chimchar',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		391 => array('name' => 'Monferno',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		392 => array('name' => 'Infernape',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		393 => array('name' => 'Piplup',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		394 => array('name' => 'Prinplup',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		395 => array('name' => 'Empoleon',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		396 => array('name' => 'Starly',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		397 => array('name' => 'Staravia',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		398 => array('name' => 'Staraptor',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		399 => array('name' => 'Bidoof',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		400 => array('name' => 'Bibarel',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		401 => array('name' => 'Kricketot',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		402 => array('name' => 'Kricketune',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		403 => array('name' => 'Shinx',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		404 => array('name' => 'Luxio',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		405 => array('name' => 'Luxray',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		406 => array('name' => 'Budew',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		407 => array('name' => 'Roserade',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		408 => array('name' => 'Cranidos',    'experience' => self::EXPERIENCE_ERRATIC),
		409 => array('name' => 'Rampardos',   'experience' => self::EXPERIENCE_ERRATIC),
		410 => array('name' => 'Shieldon',    'experience' => self::EXPERIENCE_ERRATIC),
		411 => array('name' => 'Bastiodon',   'experience' => self::EXPERIENCE_ERRATIC),
		412 => array('name' => 'Burmy',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		413 => array('name' => 'Wormadam',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		414 => array('name' => 'Mothim',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		415 => array('name' => 'Combee',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		416 => array('name' => 'Vespiquen',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		417 => array('name' => 'Pachirisu',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		418 => array('name' => 'Buizel',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		419 => array('name' => 'Floatzel',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		420 => array('name' => 'Cherubi',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		421 => array('name' => 'Cherrim',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		422 => array('name' => 'Shellos',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		423 => array('name' => 'Gastrodon',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		424 => array('name' => 'Ambipom',     'experience' => self::EXPERIENCE_FAST),
		425 => array('name' => 'Drifloon',    'experience' => self::EXPERIENCE_FLUCTUATING),
		426 => array('name' => 'Drifblim',    'experience' => self::EXPERIENCE_FLUCTUATING),
		427 => array('name' => 'Buneary',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		428 => array('name' => 'Lopunny',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		429 => array('name' => 'Mismagius',   'experience' => self::EXPERIENCE_FAST),
		430 => array('name' => 'Honchkrow',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		431 => array('name' => 'Glameow',     'experience' => self::EXPERIENCE_FAST),
		432 => array('name' => 'Purugly',     'experience' => self::EXPERIENCE_FAST),
		433 => array('name' => 'Chingling',   'experience' => self::EXPERIENCE_FAST),
		434 => array('name' => 'Stunky',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		435 => array('name' => 'Skuntank',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		436 => array('name' => 'Bronzor',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		437 => array('name' => 'Bronzong',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		438 => array('name' => 'Bonsly',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		439 => array('name' => 'Mime Jr.',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		440 => array('name' => 'Happiny',     'experience' => self::EXPERIENCE_FAST),
		441 => array('name' => 'Chatot',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		442 => array('name' => 'Spiritomb',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		443 => array('name' => 'Gible',       'experience' => self::EXPERIENCE_SLOW),
		444 => array('name' => 'Gabite',      'experience' => self::EXPERIENCE_SLOW),
		445 => array('name' => 'Garchomp',    'experience' => self::EXPERIENCE_SLOW),
		446 => array('name' => 'Munchlax',    'experience' => self::EXPERIENCE_SLOW),
		447 => array('name' => 'Riolu',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		448 => array('name' => 'Lucario',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		449 => array('name' => 'Hippopotas',  'experience' => self::EXPERIENCE_SLOW),
		450 => array('name' => 'Hippowdon',   'experience' => self::EXPERIENCE_SLOW),
		451 => array('name' => 'Skorupi',     'experience' => self::EXPERIENCE_SLOW),
		452 => array('name' => 'Drapion',     'experience' => self::EXPERIENCE_SLOW),
		453 => array('name' => 'Croagunk',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		454 => array('name' => 'Toxicroak',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		455 => array('name' => 'Carnivine',   'experience' => self::EXPERIENCE_SLOW),
		456 => array('name' => 'Finneon',     'experience' => self::EXPERIENCE_ERRATIC),
		457 => array('name' => 'Lumineon',    'experience' => self::EXPERIENCE_ERRATIC),
		458 => array('name' => 'Mantyke',     'experience' => self::EXPERIENCE_SLOW),
		459 => array('name' => 'Snover',      'experience' => self::EXPERIENCE_SLOW),
		460 => array('name' => 'Abomasnow',   'experience' => self::EXPERIENCE_SLOW),
		461 => array('name' => 'Weavile',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		462 => array('name' => 'Magnezone',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		463 => array('name' => 'Lickilicky',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		464 => array('name' => 'Rhyperior',   'experience' => self::EXPERIENCE_SLOW),
		465 => array('name' => 'Tangrowth',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		466 => array('name' => 'Electivire',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		467 => array('name' => 'Magmortar',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		468 => array('name' => 'Togekiss',    'experience' => self::EXPERIENCE_FAST),
		469 => array('name' => 'Yanmega',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		470 => array('name' => 'Leafeon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		471 => array('name' => 'Glaceon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		472 => array('name' => 'Gliscor',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		473 => array('name' => 'Mamoswine',   'experience' => self::EXPERIENCE_SLOW),
		474 => array('name' => 'Porygon-Z',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		475 => array('name' => 'Gallade',     'experience' => self::EXPERIENCE_SLOW),
		476 => array('name' => 'Probopass',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		477 => array('name' => 'Dusknoir',    'experience' => self::EXPERIENCE_FAST),
		478 => array('name' => 'Froslass',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		479 => array('name' => 'Rotom',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		480 => array('name' => 'Uxie',        'experience' => self::EXPERIENCE_SLOW),
		481 => array('name' => 'Mesprit',     'experience' => self::EXPERIENCE_SLOW),
		482 => array('name' => 'Azelf',       'experience' => self::EXPERIENCE_SLOW),
		483 => array('name' => 'Dialga',      'experience' => self::EXPERIENCE_SLOW),
		484 => array('name' => 'Palkia',      'experience' => self::EXPERIENCE_SLOW),
		485 => array('name' => 'Heatran',     'experience' => self::EXPERIENCE_SLOW),
		486 => array('name' => 'Regigigas',   'experience' => self::EXPERIENCE_SLOW),
		487 => array('name' => 'Giratina',    'experience' => self::EXPERIENCE_SLOW),
		488 => array('name' => 'Cresselia',   'experience' => self::EXPERIENCE_SLOW),
		489 => array('name' => 'Phione',      'experience' => self::EXPERIENCE_SLOW),
		490 => array('name' => 'Manaphy',     'experience' => self::EXPERIENCE_SLOW),
		491 => array('name' => 'Darkrai',     'experience' => self::EXPERIENCE_SLOW),
		492 => array('name' => 'Shaymin',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		493 => array('name' => 'Arceus',      'experience' => self::EXPERIENCE_SLOW),
		494 => array('name' => 'Victini',     'experience' => self::EXPERIENCE_SLOW),
		495 => array('name' => 'Snivy',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		496 => array('name' => 'Servine',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		497 => array('name' => 'Serperior',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		498 => array('name' => 'Tepig',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		499 => array('name' => 'Pignite',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		500 => array('name' => 'Emboar',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		501 => array('name' => 'Oshawott',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		502 => array('name' => 'Dewott',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		503 => array('name' => 'Samurott',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		504 => array('name' => 'Patrat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		505 => array('name' => 'Watchog',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		506 => array('name' => 'Lillipup',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		507 => array('name' => 'Herdier',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		508 => array('name' => 'Stoutland',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		509 => array('name' => 'Purrloin',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		510 => array('name' => 'Liepard',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		511 => array('name' => 'Pansage',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		512 => array('name' => 'Simisage',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		513 => array('name' => 'Pansear',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		514 => array('name' => 'Simisear',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		515 => array('name' => 'Panpour',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		516 => array('name' => 'Simipour',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		517 => array('name' => 'Munna',       'experience' => self::EXPERIENCE_FAST),
		518 => array('name' => 'Musharna',    'experience' => self::EXPERIENCE_FAST),
		519 => array('name' => 'Pidove',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		520 => array('name' => 'Tranquill',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		521 => array('name' => 'Unfezant',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		522 => array('name' => 'Blitzle',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		523 => array('name' => 'Zebstrika',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		524 => array('name' => 'Roggenrola',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		525 => array('name' => 'Boldore',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		526 => array('name' => 'Gigalith',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		527 => array('name' => 'Woobat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		528 => array('name' => 'Swoobat',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		529 => array('name' => 'Drilbur',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		530 => array('name' => 'Excadrill',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		531 => array('name' => 'Audino',      'experience' => self::EXPERIENCE_FAST),
		532 => array('name' => 'Timburr',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		533 => array('name' => 'Gurdurr',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		534 => array('name' => 'Conkeldurr',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		535 => array('name' => 'Tympole',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		536 => array('name' => 'Palpitoad',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		537 => array('name' => 'Seismitoad',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		538 => array('name' => 'Throh',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		539 => array('name' => 'Sawk',        'experience' => self::EXPERIENCE_MEDIUM_FAST),
		540 => array('name' => 'Sewaddle',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		541 => array('name' => 'Swadloon',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		542 => array('name' => 'Leavanny',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		543 => array('name' => 'Venipede',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		544 => array('name' => 'Whirlipede',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		545 => array('name' => 'Scolipede',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		546 => array('name' => 'Cottonee',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		547 => array('name' => 'Whimsicott',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		548 => array('name' => 'Petilil',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		549 => array('name' => 'Lilligant',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		550 => array('name' => 'Basculin',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		551 => array('name' => 'Sandile',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		552 => array('name' => 'Krokorok',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		553 => array('name' => 'Krookodile',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		554 => array('name' => 'Darumaka',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		555 => array('name' => 'Darmanitan',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		556 => array('name' => 'Maractus',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		557 => array('name' => 'Dwebble',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		558 => array('name' => 'Crustle',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		559 => array('name' => 'Scraggy',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		560 => array('name' => 'Scrafty',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		561 => array('name' => 'Sigilyph',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		562 => array('name' => 'Yamask',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		563 => array('name' => 'Cofagrigus',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		564 => array('name' => 'Tirtouga',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		565 => array('name' => 'Carracosta',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		566 => array('name' => 'Archen',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		567 => array('name' => 'Archeops',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		568 => array('name' => 'Trubbish',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		569 => array('name' => 'Garbodor',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		570 => array('name' => 'Zorua',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		571 => array('name' => 'Zoroark',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		572 => array('name' => 'Minccino',    'experience' => self::EXPERIENCE_FAST),
		573 => array('name' => 'Cinccino',    'experience' => self::EXPERIENCE_FAST),
		574 => array('name' => 'Gothita',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		575 => array('name' => 'Gothorita',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		576 => array('name' => 'Gothitelle',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		577 => array('name' => 'Solosis',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		578 => array('name' => 'Duosion',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		579 => array('name' => 'Reuniclus',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		580 => array('name' => 'Ducklett',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		581 => array('name' => 'Swanna',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		582 => array('name' => 'Vanillite',   'experience' => self::EXPERIENCE_SLOW),
		583 => array('name' => 'Vanillish',   'experience' => self::EXPERIENCE_SLOW),
		584 => array('name' => 'Vanilluxe',   'experience' => self::EXPERIENCE_SLOW),
		585 => array('name' => 'Deerling',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		586 => array('name' => 'Sawsbuck',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		587 => array('name' => 'Emolga',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		588 => array('name' => 'Karrablast',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		589 => array('name' => 'Escavalier',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		590 => array('name' => 'Foongus',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		591 => array('name' => 'Amoonguss',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		592 => array('name' => 'Frillish',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		593 => array('name' => 'Jellicent',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		594 => array('name' => 'Alomomola',   'experience' => self::EXPERIENCE_FAST),
		595 => array('name' => 'Joltik',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		596 => array('name' => 'Galvantula',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		597 => array('name' => 'Ferroseed',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		598 => array('name' => 'Ferrothorn',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		599 => array('name' => 'Klink',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		600 => array('name' => 'Klang',       'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		601 => array('name' => 'Klinklang',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		602 => array('name' => 'Tynamo',      'experience' => self::EXPERIENCE_SLOW),
		603 => array('name' => 'Eelektrik',   'experience' => self::EXPERIENCE_SLOW),
		604 => array('name' => 'Eelektross',  'experience' => self::EXPERIENCE_SLOW),
		605 => array('name' => 'Elgyem',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		606 => array('name' => 'Beheeyem',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		607 => array('name' => 'Litwick',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		608 => array('name' => 'Lampent',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		609 => array('name' => 'Chandelure',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		610 => array('name' => 'Axew',        'experience' => self::EXPERIENCE_SLOW),
		611 => array('name' => 'Fraxure',     'experience' => self::EXPERIENCE_SLOW),
		612 => array('name' => 'Haxorus',     'experience' => self::EXPERIENCE_SLOW),
		613 => array('name' => 'Cubchoo',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		614 => array('name' => 'Beartic',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		615 => array('name' => 'Cryogonal',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		616 => array('name' => 'Shelmet',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		617 => array('name' => 'Accelgor',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		618 => array('name' => 'Stunfisk',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		619 => array('name' => 'Mienfoo',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		620 => array('name' => 'Mienshao',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		621 => array('name' => 'Druddigon',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		622 => array('name' => 'Golett',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		623 => array('name' => 'Golurk',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		624 => array('name' => 'Pawniard',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		625 => array('name' => 'Bisharp',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		626 => array('name' => 'Bouffalant',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		627 => array('name' => 'Rufflet',     'experience' => self::EXPERIENCE_SLOW),
		628 => array('name' => 'Braviary',    'experience' => self::EXPERIENCE_SLOW),
		629 => array('name' => 'Vullaby',     'experience' => self::EXPERIENCE_SLOW),
		630 => array('name' => 'Mandibuzz ',  'experience' => self::EXPERIENCE_SLOW),
		631 => array('name' => 'Heatmor',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		632 => array('name' => 'Durant',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		633 => array('name' => 'Deino',       'experience' => self::EXPERIENCE_SLOW),
		634 => array('name' => 'Zweilous',    'experience' => self::EXPERIENCE_SLOW),
		635 => array('name' => 'Hydreigon',   'experience' => self::EXPERIENCE_SLOW),
		636 => array('name' => 'Larvesta',    'experience' => self::EXPERIENCE_SLOW),
		637 => array('name' => 'Volcarona',   'experience' => self::EXPERIENCE_SLOW),
		638 => array('name' => 'Cobalion',    'experience' => self::EXPERIENCE_SLOW),
		639 => array('name' => 'Terrakion',   'experience' => self::EXPERIENCE_SLOW),
		640 => array('name' => 'Virizion',    'experience' => self::EXPERIENCE_SLOW),
		641 => array('name' => 'Tornadus',    'experience' => self::EXPERIENCE_SLOW),
		642 => array('name' => 'Thundurus',   'experience' => self::EXPERIENCE_SLOW),
		643 => array('name' => 'Reshiram',    'experience' => self::EXPERIENCE_SLOW),
		644 => array('name' => 'Zekrom ',     'experience' => self::EXPERIENCE_SLOW),
		645 => array('name' => 'Landorus',    'experience' => self::EXPERIENCE_SLOW),
		646 => array('name' => 'Kyurem',      'experience' => self::EXPERIENCE_SLOW),
		647 => array('name' => 'Keldeo',      'experience' => self::EXPERIENCE_SLOW),
		648 => array('name' => 'Meloetta',    'experience' => self::EXPERIENCE_SLOW),
		649 => array('name' => 'Genesect',    'experience' => self::EXPERIENCE_SLOW),
		650 => array('name' => 'Chespin',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		651 => array('name' => 'Quilladin',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		652 => array('name' => 'Chesnaught',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		653 => array('name' => 'Fennekin',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		654 => array('name' => 'Braixen',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		655 => array('name' => 'Delphox',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		656 => array('name' => 'Froakie',     'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		657 => array('name' => 'Frogadier',   'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		658 => array('name' => 'Greninja',    'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		659 => array('name' => 'Bunnelby',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		660 => array('name' => 'Diggersby',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		661 => array('name' => 'Fletchling',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		662 => array('name' => 'Fletchinder', 'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		663 => array('name' => 'Talonflame',  'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		664 => array('name' => 'Scatterbug',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		665 => array('name' => 'Spewpa',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		666 => array('name' => 'Vivillon',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		667 => array('name' => 'Litleo',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		668 => array('name' => 'Pyroar',      'experience' => self::EXPERIENCE_MEDIUM_SLOW),
		669 => array('name' => 'Flabébé',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		670 => array('name' => 'Floette',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		671 => array('name' => 'Florges',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		672 => array('name' => 'Skiddo',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		673 => array('name' => 'Gogoat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		674 => array('name' => 'Pancham',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		675 => array('name' => 'Pangoro',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		676 => array('name' => 'Furfrou',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		677 => array('name' => 'Espurr',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		678 => array('name' => 'Meowstic',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		679 => array('name' => 'Honedge',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		680 => array('name' => 'Doublade',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		681 => array('name' => 'Aegislash',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		682 => array('name' => 'Spritzee',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		683 => array('name' => 'Aromatisse',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		684 => array('name' => 'Swirlix',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		685 => array('name' => 'Slurpuff',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		686 => array('name' => 'Inkay',       'experience' => self::EXPERIENCE_MEDIUM_FAST),
		687 => array('name' => 'Malamar',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		688 => array('name' => 'Binacle',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		689 => array('name' => 'Barbaracle',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		690 => array('name' => 'Skrelp',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		691 => array('name' => 'Dragalge',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		692 => array('name' => 'Clauncher',   'experience' => self::EXPERIENCE_SLOW),
		693 => array('name' => 'Clawitzer',   'experience' => self::EXPERIENCE_SLOW),
		694 => array('name' => 'Helioptile',  'experience' => self::EXPERIENCE_MEDIUM_FAST),
		695 => array('name' => 'Heliolisk',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		696 => array('name' => 'Tyrunt',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		697 => array('name' => 'Tyrantrum',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		698 => array('name' => 'Amaura',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		699 => array('name' => 'Aurorus',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		700 => array('name' => 'Sylveon',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		701 => array('name' => 'Hawlucha',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		702 => array('name' => 'Dedenne',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		703 => array('name' => 'Carbink',     'experience' => self::EXPERIENCE_SLOW),
		704 => array('name' => 'Goomy',       'experience' => self::EXPERIENCE_SLOW),
		705 => array('name' => 'Sliggoo',     'experience' => self::EXPERIENCE_SLOW),
		706 => array('name' => 'Goodra',      'experience' => self::EXPERIENCE_SLOW),
		707 => array('name' => 'Klefki',      'experience' => self::EXPERIENCE_FAST),
		708 => array('name' => 'Phantump',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		709 => array('name' => 'Trevenant',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		710 => array('name' => 'Pumpkaboo',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		711 => array('name' => 'Gourgeist',   'experience' => self::EXPERIENCE_MEDIUM_FAST),
		712 => array('name' => 'Bergmite',    'experience' => self::EXPERIENCE_MEDIUM_FAST),
		713 => array('name' => 'Avalugg',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		714 => array('name' => 'Noibat',      'experience' => self::EXPERIENCE_MEDIUM_FAST),
		715 => array('name' => 'Noivern',     'experience' => self::EXPERIENCE_MEDIUM_FAST),
		716 => array('name' => 'Xerneas',     'experience' => self::EXPERIENCE_SLOW),
		717 => array('name' => 'Yveltal',     'experience' => self::EXPERIENCE_SLOW),
		718 => array('name' => 'Zygarde',     'experience' => self::EXPERIENCE_SLOW),
		719 => array('name' => 'Diancie',     'experience' => self::EXPERIENCE_SLOW),
		720 => array('name' => 'Hoopa',       'experience' => self::EXPERIENCE_SLOW),
		721 => array('name' => 'Volcanion',   'experience' => self::EXPERIENCE_SLOW)
		);
	
	protected static $experienceTable = array(
		1   => array(self::EXPERIENCE_SLOW => 0,       self::EXPERIENCE_MEDIUM_SLOW => 0,       self::EXPERIENCE_MEDIUM_FAST => 0,       self::EXPERIENCE_FAST => 0,      self::EXPERIENCE_ERRATIC => 0,      self::EXPERIENCE_FLUCTUATING => 0       ),
		2   => array(self::EXPERIENCE_SLOW => 10,      self::EXPERIENCE_MEDIUM_SLOW => 9,       self::EXPERIENCE_MEDIUM_FAST => 8,       self::EXPERIENCE_FAST => 6,      self::EXPERIENCE_ERRATIC => 15,     self::EXPERIENCE_FLUCTUATING => 4       ),
		3   => array(self::EXPERIENCE_SLOW => 33,      self::EXPERIENCE_MEDIUM_SLOW => 57,      self::EXPERIENCE_MEDIUM_FAST => 27,      self::EXPERIENCE_FAST => 21,     self::EXPERIENCE_ERRATIC => 52,     self::EXPERIENCE_FLUCTUATING => 13      ),
		4   => array(self::EXPERIENCE_SLOW => 80,      self::EXPERIENCE_MEDIUM_SLOW => 96,      self::EXPERIENCE_MEDIUM_FAST => 64,      self::EXPERIENCE_FAST => 51,     self::EXPERIENCE_ERRATIC => 122,    self::EXPERIENCE_FLUCTUATING => 32      ),
		5   => array(self::EXPERIENCE_SLOW => 156,     self::EXPERIENCE_MEDIUM_SLOW => 135,     self::EXPERIENCE_MEDIUM_FAST => 125,     self::EXPERIENCE_FAST => 100,    self::EXPERIENCE_ERRATIC => 237,    self::EXPERIENCE_FLUCTUATING => 65      ),
		6   => array(self::EXPERIENCE_SLOW => 270,     self::EXPERIENCE_MEDIUM_SLOW => 179,     self::EXPERIENCE_MEDIUM_FAST => 216,     self::EXPERIENCE_FAST => 172,    self::EXPERIENCE_ERRATIC => 406,    self::EXPERIENCE_FLUCTUATING => 112     ),
		7   => array(self::EXPERIENCE_SLOW => 428,     self::EXPERIENCE_MEDIUM_SLOW => 236,     self::EXPERIENCE_MEDIUM_FAST => 343,     self::EXPERIENCE_FAST => 274,    self::EXPERIENCE_ERRATIC => 637,    self::EXPERIENCE_FLUCTUATING => 178     ),
		8   => array(self::EXPERIENCE_SLOW => 640,     self::EXPERIENCE_MEDIUM_SLOW => 314,     self::EXPERIENCE_MEDIUM_FAST => 512,     self::EXPERIENCE_FAST => 409,    self::EXPERIENCE_ERRATIC => 942,    self::EXPERIENCE_FLUCTUATING => 276     ),
		9   => array(self::EXPERIENCE_SLOW => 911,     self::EXPERIENCE_MEDIUM_SLOW => 419,     self::EXPERIENCE_MEDIUM_FAST => 729,     self::EXPERIENCE_FAST => 583,    self::EXPERIENCE_ERRATIC => 1326,   self::EXPERIENCE_FLUCTUATING => 393     ),
		10  => array(self::EXPERIENCE_SLOW => 1250,    self::EXPERIENCE_MEDIUM_SLOW => 560,     self::EXPERIENCE_MEDIUM_FAST => 1000,    self::EXPERIENCE_FAST => 800,    self::EXPERIENCE_ERRATIC => 1800,   self::EXPERIENCE_FLUCTUATING => 540     ),
		11  => array(self::EXPERIENCE_SLOW => 1663,    self::EXPERIENCE_MEDIUM_SLOW => 742,     self::EXPERIENCE_MEDIUM_FAST => 1331,    self::EXPERIENCE_FAST => 1064,   self::EXPERIENCE_ERRATIC => 2369,   self::EXPERIENCE_FLUCTUATING => 745     ),
		12  => array(self::EXPERIENCE_SLOW => 2160,    self::EXPERIENCE_MEDIUM_SLOW => 973,     self::EXPERIENCE_MEDIUM_FAST => 1728,    self::EXPERIENCE_FAST => 1382,   self::EXPERIENCE_ERRATIC => 3041,   self::EXPERIENCE_FLUCTUATING => 967     ),
		13  => array(self::EXPERIENCE_SLOW => 2746,    self::EXPERIENCE_MEDIUM_SLOW => 1261,    self::EXPERIENCE_MEDIUM_FAST => 2197,    self::EXPERIENCE_FAST => 1757,   self::EXPERIENCE_ERRATIC => 3822,   self::EXPERIENCE_FLUCTUATING => 1230    ),
		14  => array(self::EXPERIENCE_SLOW => 3430,    self::EXPERIENCE_MEDIUM_SLOW => 1612,    self::EXPERIENCE_MEDIUM_FAST => 2744,    self::EXPERIENCE_FAST => 2195,   self::EXPERIENCE_ERRATIC => 4719,   self::EXPERIENCE_FLUCTUATING => 1591    ),
		15  => array(self::EXPERIENCE_SLOW => 4218,    self::EXPERIENCE_MEDIUM_SLOW => 2035,    self::EXPERIENCE_MEDIUM_FAST => 3375,    self::EXPERIENCE_FAST => 2700,   self::EXPERIENCE_ERRATIC => 5737,   self::EXPERIENCE_FLUCTUATING => 1957    ),
		16  => array(self::EXPERIENCE_SLOW => 5120,    self::EXPERIENCE_MEDIUM_SLOW => 2535,    self::EXPERIENCE_MEDIUM_FAST => 4096,    self::EXPERIENCE_FAST => 3276,   self::EXPERIENCE_ERRATIC => 6881,   self::EXPERIENCE_FLUCTUATING => 2457    ),
		17  => array(self::EXPERIENCE_SLOW => 6141,    self::EXPERIENCE_MEDIUM_SLOW => 3120,    self::EXPERIENCE_MEDIUM_FAST => 4913,    self::EXPERIENCE_FAST => 3930,   self::EXPERIENCE_ERRATIC => 8155,   self::EXPERIENCE_FLUCTUATING => 3046    ),
		18  => array(self::EXPERIENCE_SLOW => 7290,    self::EXPERIENCE_MEDIUM_SLOW => 3798,    self::EXPERIENCE_MEDIUM_FAST => 5832,    self::EXPERIENCE_FAST => 4665,   self::EXPERIENCE_ERRATIC => 9564,   self::EXPERIENCE_FLUCTUATING => 3732    ),
		19  => array(self::EXPERIENCE_SLOW => 8573,    self::EXPERIENCE_MEDIUM_SLOW => 4575,    self::EXPERIENCE_MEDIUM_FAST => 6859,    self::EXPERIENCE_FAST => 5487,   self::EXPERIENCE_ERRATIC => 11111,  self::EXPERIENCE_FLUCTUATING => 4526    ),
		20  => array(self::EXPERIENCE_SLOW => 10000,   self::EXPERIENCE_MEDIUM_SLOW => 5460,    self::EXPERIENCE_MEDIUM_FAST => 8000,    self::EXPERIENCE_FAST => 6400,   self::EXPERIENCE_ERRATIC => 12800,  self::EXPERIENCE_FLUCTUATING => 5440    ),
		21  => array(self::EXPERIENCE_SLOW => 11576,   self::EXPERIENCE_MEDIUM_SLOW => 6458,    self::EXPERIENCE_MEDIUM_FAST => 9261,    self::EXPERIENCE_FAST => 7408,   self::EXPERIENCE_ERRATIC => 14632,  self::EXPERIENCE_FLUCTUATING => 6482    ),
		22  => array(self::EXPERIENCE_SLOW => 13310,   self::EXPERIENCE_MEDIUM_SLOW => 7577,    self::EXPERIENCE_MEDIUM_FAST => 10648,   self::EXPERIENCE_FAST => 8518,   self::EXPERIENCE_ERRATIC => 16610,  self::EXPERIENCE_FLUCTUATING => 7666    ),
		23  => array(self::EXPERIENCE_SLOW => 15208,   self::EXPERIENCE_MEDIUM_SLOW => 8825,    self::EXPERIENCE_MEDIUM_FAST => 12167,   self::EXPERIENCE_FAST => 9733,   self::EXPERIENCE_ERRATIC => 18737,  self::EXPERIENCE_FLUCTUATING => 9003    ),
		24  => array(self::EXPERIENCE_SLOW => 17280,   self::EXPERIENCE_MEDIUM_SLOW => 10208,   self::EXPERIENCE_MEDIUM_FAST => 13824,   self::EXPERIENCE_FAST => 11059,  self::EXPERIENCE_ERRATIC => 21012,  self::EXPERIENCE_FLUCTUATING => 10506   ),
		25  => array(self::EXPERIENCE_SLOW => 19531,   self::EXPERIENCE_MEDIUM_SLOW => 11735,   self::EXPERIENCE_MEDIUM_FAST => 15625,   self::EXPERIENCE_FAST => 12500,  self::EXPERIENCE_ERRATIC => 23437,  self::EXPERIENCE_FLUCTUATING => 12187   ),
		26  => array(self::EXPERIENCE_SLOW => 21970,   self::EXPERIENCE_MEDIUM_SLOW => 13411,   self::EXPERIENCE_MEDIUM_FAST => 17576,   self::EXPERIENCE_FAST => 14060,  self::EXPERIENCE_ERRATIC => 26012,  self::EXPERIENCE_FLUCTUATING => 14060   ),
		27  => array(self::EXPERIENCE_SLOW => 24603,   self::EXPERIENCE_MEDIUM_SLOW => 15244,   self::EXPERIENCE_MEDIUM_FAST => 19683,   self::EXPERIENCE_FAST => 15746,  self::EXPERIENCE_ERRATIC => 28737,  self::EXPERIENCE_FLUCTUATING => 16140   ),
		28  => array(self::EXPERIENCE_SLOW => 27440,   self::EXPERIENCE_MEDIUM_SLOW => 17242,   self::EXPERIENCE_MEDIUM_FAST => 21952,   self::EXPERIENCE_FAST => 17561,  self::EXPERIENCE_ERRATIC => 31610,  self::EXPERIENCE_FLUCTUATING => 18439   ),
		29  => array(self::EXPERIENCE_SLOW => 30486,   self::EXPERIENCE_MEDIUM_SLOW => 19411,   self::EXPERIENCE_MEDIUM_FAST => 24389,   self::EXPERIENCE_FAST => 19511,  self::EXPERIENCE_ERRATIC => 34632,  self::EXPERIENCE_FLUCTUATING => 20974   ),
		30  => array(self::EXPERIENCE_SLOW => 33750,   self::EXPERIENCE_MEDIUM_SLOW => 21760,   self::EXPERIENCE_MEDIUM_FAST => 27000,   self::EXPERIENCE_FAST => 21600,  self::EXPERIENCE_ERRATIC => 37800,  self::EXPERIENCE_FLUCTUATING => 23760   ),
		31  => array(self::EXPERIENCE_SLOW => 37238,   self::EXPERIENCE_MEDIUM_SLOW => 24294,   self::EXPERIENCE_MEDIUM_FAST => 29791,   self::EXPERIENCE_FAST => 23832,  self::EXPERIENCE_ERRATIC => 41111,  self::EXPERIENCE_FLUCTUATING => 26811   ),
		32  => array(self::EXPERIENCE_SLOW => 40960,   self::EXPERIENCE_MEDIUM_SLOW => 27021,   self::EXPERIENCE_MEDIUM_FAST => 32768,   self::EXPERIENCE_FAST => 26214,  self::EXPERIENCE_ERRATIC => 44564,  self::EXPERIENCE_FLUCTUATING => 30146   ),
		33  => array(self::EXPERIENCE_SLOW => 44921,   self::EXPERIENCE_MEDIUM_SLOW => 29949,   self::EXPERIENCE_MEDIUM_FAST => 35937,   self::EXPERIENCE_FAST => 28749,  self::EXPERIENCE_ERRATIC => 48155,  self::EXPERIENCE_FLUCTUATING => 33780   ),
		34  => array(self::EXPERIENCE_SLOW => 49130,   self::EXPERIENCE_MEDIUM_SLOW => 33084,   self::EXPERIENCE_MEDIUM_FAST => 39304,   self::EXPERIENCE_FAST => 31443,  self::EXPERIENCE_ERRATIC => 51881,  self::EXPERIENCE_FLUCTUATING => 37731   ),
		35  => array(self::EXPERIENCE_SLOW => 53593,   self::EXPERIENCE_MEDIUM_SLOW => 36435,   self::EXPERIENCE_MEDIUM_FAST => 42875,   self::EXPERIENCE_FAST => 34300,  self::EXPERIENCE_ERRATIC => 55737,  self::EXPERIENCE_FLUCTUATING => 42017   ),
		36  => array(self::EXPERIENCE_SLOW => 58320,   self::EXPERIENCE_MEDIUM_SLOW => 40007,   self::EXPERIENCE_MEDIUM_FAST => 46656,   self::EXPERIENCE_FAST => 37324,  self::EXPERIENCE_ERRATIC => 59719,  self::EXPERIENCE_FLUCTUATING => 46656   ),
		37  => array(self::EXPERIENCE_SLOW => 63316,   self::EXPERIENCE_MEDIUM_SLOW => 43808,   self::EXPERIENCE_MEDIUM_FAST => 50653,   self::EXPERIENCE_FAST => 40522,  self::EXPERIENCE_ERRATIC => 63822,  self::EXPERIENCE_FLUCTUATING => 50653   ),
		38  => array(self::EXPERIENCE_SLOW => 68590,   self::EXPERIENCE_MEDIUM_SLOW => 47846,   self::EXPERIENCE_MEDIUM_FAST => 54872,   self::EXPERIENCE_FAST => 43897,  self::EXPERIENCE_ERRATIC => 68041,  self::EXPERIENCE_FLUCTUATING => 55969   ),
		39  => array(self::EXPERIENCE_SLOW => 74148,   self::EXPERIENCE_MEDIUM_SLOW => 52127,   self::EXPERIENCE_MEDIUM_FAST => 59319,   self::EXPERIENCE_FAST => 47455,  self::EXPERIENCE_ERRATIC => 72369,  self::EXPERIENCE_FLUCTUATING => 60505   ),
		40  => array(self::EXPERIENCE_SLOW => 80000,   self::EXPERIENCE_MEDIUM_SLOW => 56660,   self::EXPERIENCE_MEDIUM_FAST => 64000,   self::EXPERIENCE_FAST => 51200,  self::EXPERIENCE_ERRATIC => 76800,  self::EXPERIENCE_FLUCTUATING => 66560   ),
		41  => array(self::EXPERIENCE_SLOW => 86151,   self::EXPERIENCE_MEDIUM_SLOW => 61450,   self::EXPERIENCE_MEDIUM_FAST => 68921,   self::EXPERIENCE_FAST => 55136,  self::EXPERIENCE_ERRATIC => 81326,  self::EXPERIENCE_FLUCTUATING => 71677   ),
		42  => array(self::EXPERIENCE_SLOW => 92610,   self::EXPERIENCE_MEDIUM_SLOW => 66505,   self::EXPERIENCE_MEDIUM_FAST => 74088,   self::EXPERIENCE_FAST => 59270,  self::EXPERIENCE_ERRATIC => 85942,  self::EXPERIENCE_FLUCTUATING => 78533   ),
		43  => array(self::EXPERIENCE_SLOW => 99383,   self::EXPERIENCE_MEDIUM_SLOW => 71833,   self::EXPERIENCE_MEDIUM_FAST => 79507,   self::EXPERIENCE_FAST => 63605,  self::EXPERIENCE_ERRATIC => 90637,  self::EXPERIENCE_FLUCTUATING => 84277   ),
		44  => array(self::EXPERIENCE_SLOW => 106480,  self::EXPERIENCE_MEDIUM_SLOW => 77440,   self::EXPERIENCE_MEDIUM_FAST => 85184,   self::EXPERIENCE_FAST => 68147,  self::EXPERIENCE_ERRATIC => 95406,  self::EXPERIENCE_FLUCTUATING => 91998   ),
		45  => array(self::EXPERIENCE_SLOW => 113906,  self::EXPERIENCE_MEDIUM_SLOW => 83335,   self::EXPERIENCE_MEDIUM_FAST => 91125,   self::EXPERIENCE_FAST => 72900,  self::EXPERIENCE_ERRATIC => 100237, self::EXPERIENCE_FLUCTUATING => 98415   ),
		46  => array(self::EXPERIENCE_SLOW => 121670,  self::EXPERIENCE_MEDIUM_SLOW => 89523,   self::EXPERIENCE_MEDIUM_FAST => 97336,   self::EXPERIENCE_FAST => 77868,  self::EXPERIENCE_ERRATIC => 105122, self::EXPERIENCE_FLUCTUATING => 107069  ),
		47  => array(self::EXPERIENCE_SLOW => 129778,  self::EXPERIENCE_MEDIUM_SLOW => 96012,   self::EXPERIENCE_MEDIUM_FAST => 103823,  self::EXPERIENCE_FAST => 83058,  self::EXPERIENCE_ERRATIC => 110052, self::EXPERIENCE_FLUCTUATING => 114205  ),
		48  => array(self::EXPERIENCE_SLOW => 138240,  self::EXPERIENCE_MEDIUM_SLOW => 102810,  self::EXPERIENCE_MEDIUM_FAST => 110592,  self::EXPERIENCE_FAST => 88473,  self::EXPERIENCE_ERRATIC => 115015, self::EXPERIENCE_FLUCTUATING => 123863  ),
		49  => array(self::EXPERIENCE_SLOW => 147061,  self::EXPERIENCE_MEDIUM_SLOW => 109923,  self::EXPERIENCE_MEDIUM_FAST => 117649,  self::EXPERIENCE_FAST => 94119,  self::EXPERIENCE_ERRATIC => 120001, self::EXPERIENCE_FLUCTUATING => 131766  ),
		50  => array(self::EXPERIENCE_SLOW => 156250,  self::EXPERIENCE_MEDIUM_SLOW => 117360,  self::EXPERIENCE_MEDIUM_FAST => 125000,  self::EXPERIENCE_FAST => 100000, self::EXPERIENCE_ERRATIC => 125000, self::EXPERIENCE_FLUCTUATING => 142500  ),
		51  => array(self::EXPERIENCE_SLOW => 165813,  self::EXPERIENCE_MEDIUM_SLOW => 125126,  self::EXPERIENCE_MEDIUM_FAST => 132651,  self::EXPERIENCE_FAST => 106120, self::EXPERIENCE_ERRATIC => 131324, self::EXPERIENCE_FLUCTUATING => 151222  ),
		52  => array(self::EXPERIENCE_SLOW => 175760,  self::EXPERIENCE_MEDIUM_SLOW => 133229,  self::EXPERIENCE_MEDIUM_FAST => 140608,  self::EXPERIENCE_FAST => 112486, self::EXPERIENCE_ERRATIC => 137795, self::EXPERIENCE_FLUCTUATING => 163105  ),
		53  => array(self::EXPERIENCE_SLOW => 186096,  self::EXPERIENCE_MEDIUM_SLOW => 141677,  self::EXPERIENCE_MEDIUM_FAST => 148877,  self::EXPERIENCE_FAST => 119101, self::EXPERIENCE_ERRATIC => 144410, self::EXPERIENCE_FLUCTUATING => 172697  ),
		54  => array(self::EXPERIENCE_SLOW => 196830,  self::EXPERIENCE_MEDIUM_SLOW => 150476,  self::EXPERIENCE_MEDIUM_FAST => 157464,  self::EXPERIENCE_FAST => 125971, self::EXPERIENCE_ERRATIC => 151165, self::EXPERIENCE_FLUCTUATING => 185807  ),
		55  => array(self::EXPERIENCE_SLOW => 207968,  self::EXPERIENCE_MEDIUM_SLOW => 159635,  self::EXPERIENCE_MEDIUM_FAST => 166375,  self::EXPERIENCE_FAST => 133100, self::EXPERIENCE_ERRATIC => 158056, self::EXPERIENCE_FLUCTUATING => 196322  ),
		56  => array(self::EXPERIENCE_SLOW => 219520,  self::EXPERIENCE_MEDIUM_SLOW => 169159,  self::EXPERIENCE_MEDIUM_FAST => 175616,  self::EXPERIENCE_FAST => 140492, self::EXPERIENCE_ERRATIC => 165079, self::EXPERIENCE_FLUCTUATING => 210739  ),
		57  => array(self::EXPERIENCE_SLOW => 231491,  self::EXPERIENCE_MEDIUM_SLOW => 179056,  self::EXPERIENCE_MEDIUM_FAST => 185193,  self::EXPERIENCE_FAST => 148154, self::EXPERIENCE_ERRATIC => 172229, self::EXPERIENCE_FLUCTUATING => 222231  ),
		58  => array(self::EXPERIENCE_SLOW => 243890,  self::EXPERIENCE_MEDIUM_SLOW => 189334,  self::EXPERIENCE_MEDIUM_FAST => 195112,  self::EXPERIENCE_FAST => 156089, self::EXPERIENCE_ERRATIC => 179503, self::EXPERIENCE_FLUCTUATING => 238036  ),
		59  => array(self::EXPERIENCE_SLOW => 256723,  self::EXPERIENCE_MEDIUM_SLOW => 199999,  self::EXPERIENCE_MEDIUM_FAST => 205379,  self::EXPERIENCE_FAST => 164303, self::EXPERIENCE_ERRATIC => 186894, self::EXPERIENCE_FLUCTUATING => 250562  ),
		60  => array(self::EXPERIENCE_SLOW => 270000,  self::EXPERIENCE_MEDIUM_SLOW => 211060,  self::EXPERIENCE_MEDIUM_FAST => 216000,  self::EXPERIENCE_FAST => 172800, self::EXPERIENCE_ERRATIC => 194400, self::EXPERIENCE_FLUCTUATING => 267840  ),
		61  => array(self::EXPERIENCE_SLOW => 283726,  self::EXPERIENCE_MEDIUM_SLOW => 222522,  self::EXPERIENCE_MEDIUM_FAST => 226981,  self::EXPERIENCE_FAST => 181584, self::EXPERIENCE_ERRATIC => 202013, self::EXPERIENCE_FLUCTUATING => 281456  ),
		62  => array(self::EXPERIENCE_SLOW => 297910,  self::EXPERIENCE_MEDIUM_SLOW => 234393,  self::EXPERIENCE_MEDIUM_FAST => 238328,  self::EXPERIENCE_FAST => 190662, self::EXPERIENCE_ERRATIC => 209728, self::EXPERIENCE_FLUCTUATING => 300293  ),
		63  => array(self::EXPERIENCE_SLOW => 312558,  self::EXPERIENCE_MEDIUM_SLOW => 246681,  self::EXPERIENCE_MEDIUM_FAST => 250047,  self::EXPERIENCE_FAST => 200037, self::EXPERIENCE_ERRATIC => 217540, self::EXPERIENCE_FLUCTUATING => 315059  ),
		64  => array(self::EXPERIENCE_SLOW => 327680,  self::EXPERIENCE_MEDIUM_SLOW => 259392,  self::EXPERIENCE_MEDIUM_FAST => 262144,  self::EXPERIENCE_FAST => 209715, self::EXPERIENCE_ERRATIC => 225443, self::EXPERIENCE_FLUCTUATING => 335544  ),
		65  => array(self::EXPERIENCE_SLOW => 343281,  self::EXPERIENCE_MEDIUM_SLOW => 272535,  self::EXPERIENCE_MEDIUM_FAST => 274625,  self::EXPERIENCE_FAST => 219700, self::EXPERIENCE_ERRATIC => 233431, self::EXPERIENCE_FLUCTUATING => 351520  ),
		66  => array(self::EXPERIENCE_SLOW => 359370,  self::EXPERIENCE_MEDIUM_SLOW => 286115,  self::EXPERIENCE_MEDIUM_FAST => 287496,  self::EXPERIENCE_FAST => 229996, self::EXPERIENCE_ERRATIC => 241496, self::EXPERIENCE_FLUCTUATING => 373744  ),
		67  => array(self::EXPERIENCE_SLOW => 375953,  self::EXPERIENCE_MEDIUM_SLOW => 300140,  self::EXPERIENCE_MEDIUM_FAST => 300763,  self::EXPERIENCE_FAST => 240610, self::EXPERIENCE_ERRATIC => 249633, self::EXPERIENCE_FLUCTUATING => 390991  ),
		68  => array(self::EXPERIENCE_SLOW => 393040,  self::EXPERIENCE_MEDIUM_SLOW => 314618,  self::EXPERIENCE_MEDIUM_FAST => 314432,  self::EXPERIENCE_FAST => 251545, self::EXPERIENCE_ERRATIC => 257834, self::EXPERIENCE_FLUCTUATING => 415050  ),
		69  => array(self::EXPERIENCE_SLOW => 410636,  self::EXPERIENCE_MEDIUM_SLOW => 329555,  self::EXPERIENCE_MEDIUM_FAST => 328509,  self::EXPERIENCE_FAST => 262807, self::EXPERIENCE_ERRATIC => 267406, self::EXPERIENCE_FLUCTUATING => 433631  ),
		70  => array(self::EXPERIENCE_SLOW => 428750,  self::EXPERIENCE_MEDIUM_SLOW => 344960,  self::EXPERIENCE_MEDIUM_FAST => 343000,  self::EXPERIENCE_FAST => 274400, self::EXPERIENCE_ERRATIC => 276458, self::EXPERIENCE_FLUCTUATING => 459620  ),
		71  => array(self::EXPERIENCE_SLOW => 447388,  self::EXPERIENCE_MEDIUM_SLOW => 360838,  self::EXPERIENCE_MEDIUM_FAST => 357911,  self::EXPERIENCE_FAST => 286328, self::EXPERIENCE_ERRATIC => 286328, self::EXPERIENCE_FLUCTUATING => 479600  ),
		72  => array(self::EXPERIENCE_SLOW => 466560,  self::EXPERIENCE_MEDIUM_SLOW => 377197,  self::EXPERIENCE_MEDIUM_FAST => 373248,  self::EXPERIENCE_FAST => 298598, self::EXPERIENCE_ERRATIC => 296358, self::EXPERIENCE_FLUCTUATING => 507617  ),
		73  => array(self::EXPERIENCE_SLOW => 486271,  self::EXPERIENCE_MEDIUM_SLOW => 394045,  self::EXPERIENCE_MEDIUM_FAST => 389017,  self::EXPERIENCE_FAST => 311213, self::EXPERIENCE_ERRATIC => 305767, self::EXPERIENCE_FLUCTUATING => 529063  ),
		74  => array(self::EXPERIENCE_SLOW => 506530,  self::EXPERIENCE_MEDIUM_SLOW => 411388,  self::EXPERIENCE_MEDIUM_FAST => 405224,  self::EXPERIENCE_FAST => 324179, self::EXPERIENCE_ERRATIC => 316074, self::EXPERIENCE_FLUCTUATING => 559209  ),
		75  => array(self::EXPERIENCE_SLOW => 527343,  self::EXPERIENCE_MEDIUM_SLOW => 429235,  self::EXPERIENCE_MEDIUM_FAST => 421875,  self::EXPERIENCE_FAST => 337500, self::EXPERIENCE_ERRATIC => 326531, self::EXPERIENCE_FLUCTUATING => 582187  ),
		76  => array(self::EXPERIENCE_SLOW => 548720,  self::EXPERIENCE_MEDIUM_SLOW => 447591,  self::EXPERIENCE_MEDIUM_FAST => 438976,  self::EXPERIENCE_FAST => 351180, self::EXPERIENCE_ERRATIC => 336255, self::EXPERIENCE_FLUCTUATING => 614566  ),
		77  => array(self::EXPERIENCE_SLOW => 570666,  self::EXPERIENCE_MEDIUM_SLOW => 466464,  self::EXPERIENCE_MEDIUM_FAST => 456533,  self::EXPERIENCE_FAST => 365226, self::EXPERIENCE_ERRATIC => 346965, self::EXPERIENCE_FLUCTUATING => 639146  ),
		78  => array(self::EXPERIENCE_SLOW => 593190,  self::EXPERIENCE_MEDIUM_SLOW => 485862,  self::EXPERIENCE_MEDIUM_FAST => 474552,  self::EXPERIENCE_FAST => 379641, self::EXPERIENCE_ERRATIC => 357812, self::EXPERIENCE_FLUCTUATING => 673863  ),
		79  => array(self::EXPERIENCE_SLOW => 616298,  self::EXPERIENCE_MEDIUM_SLOW => 505791,  self::EXPERIENCE_MEDIUM_FAST => 493039,  self::EXPERIENCE_FAST => 394431, self::EXPERIENCE_ERRATIC => 367807, self::EXPERIENCE_FLUCTUATING => 700115  ),
		80  => array(self::EXPERIENCE_SLOW => 640000,  self::EXPERIENCE_MEDIUM_SLOW => 526260,  self::EXPERIENCE_MEDIUM_FAST => 512000,  self::EXPERIENCE_FAST => 409600, self::EXPERIENCE_ERRATIC => 378880, self::EXPERIENCE_FLUCTUATING => 737280  ),
		81  => array(self::EXPERIENCE_SLOW => 664301,  self::EXPERIENCE_MEDIUM_SLOW => 547274,  self::EXPERIENCE_MEDIUM_FAST => 531441,  self::EXPERIENCE_FAST => 425152, self::EXPERIENCE_ERRATIC => 390077, self::EXPERIENCE_FLUCTUATING => 765275  ),
		82  => array(self::EXPERIENCE_SLOW => 689210,  self::EXPERIENCE_MEDIUM_SLOW => 568841,  self::EXPERIENCE_MEDIUM_FAST => 551368,  self::EXPERIENCE_FAST => 441094, self::EXPERIENCE_ERRATIC => 400293, self::EXPERIENCE_FLUCTUATING => 804997  ),
		83  => array(self::EXPERIENCE_SLOW => 714733,  self::EXPERIENCE_MEDIUM_SLOW => 590969,  self::EXPERIENCE_MEDIUM_FAST => 571787,  self::EXPERIENCE_FAST => 457429, self::EXPERIENCE_ERRATIC => 411686, self::EXPERIENCE_FLUCTUATING => 834809  ),
		84  => array(self::EXPERIENCE_SLOW => 740880,  self::EXPERIENCE_MEDIUM_SLOW => 613664,  self::EXPERIENCE_MEDIUM_FAST => 592704,  self::EXPERIENCE_FAST => 474163, self::EXPERIENCE_ERRATIC => 423190, self::EXPERIENCE_FLUCTUATING => 877201  ),
		85  => array(self::EXPERIENCE_SLOW => 767656,  self::EXPERIENCE_MEDIUM_SLOW => 636935,  self::EXPERIENCE_MEDIUM_FAST => 614125,  self::EXPERIENCE_FAST => 491300, self::EXPERIENCE_ERRATIC => 433572, self::EXPERIENCE_FLUCTUATING => 908905  ),
		86  => array(self::EXPERIENCE_SLOW => 795070,  self::EXPERIENCE_MEDIUM_SLOW => 660787,  self::EXPERIENCE_MEDIUM_FAST => 636056,  self::EXPERIENCE_FAST => 508844, self::EXPERIENCE_ERRATIC => 445239, self::EXPERIENCE_FLUCTUATING => 954084  ),
		87  => array(self::EXPERIENCE_SLOW => 823128,  self::EXPERIENCE_MEDIUM_SLOW => 685228,  self::EXPERIENCE_MEDIUM_FAST => 658503,  self::EXPERIENCE_FAST => 526802, self::EXPERIENCE_ERRATIC => 457001, self::EXPERIENCE_FLUCTUATING => 987754  ),
		88  => array(self::EXPERIENCE_SLOW => 851840,  self::EXPERIENCE_MEDIUM_SLOW => 710266,  self::EXPERIENCE_MEDIUM_FAST => 681472,  self::EXPERIENCE_FAST => 545177, self::EXPERIENCE_ERRATIC => 467489, self::EXPERIENCE_FLUCTUATING => 1035837 ),
		89  => array(self::EXPERIENCE_SLOW => 881211,  self::EXPERIENCE_MEDIUM_SLOW => 735907,  self::EXPERIENCE_MEDIUM_FAST => 704969,  self::EXPERIENCE_FAST => 563975, self::EXPERIENCE_ERRATIC => 479378, self::EXPERIENCE_FLUCTUATING => 1071552 ),
		90  => array(self::EXPERIENCE_SLOW => 911250,  self::EXPERIENCE_MEDIUM_SLOW => 762160,  self::EXPERIENCE_MEDIUM_FAST => 729000,  self::EXPERIENCE_FAST => 583200, self::EXPERIENCE_ERRATIC => 491346, self::EXPERIENCE_FLUCTUATING => 1122660 ),
		91  => array(self::EXPERIENCE_SLOW => 941963,  self::EXPERIENCE_MEDIUM_SLOW => 789030,  self::EXPERIENCE_MEDIUM_FAST => 753571,  self::EXPERIENCE_FAST => 602856, self::EXPERIENCE_ERRATIC => 501878, self::EXPERIENCE_FLUCTUATING => 1160499 ),
		92  => array(self::EXPERIENCE_SLOW => 973360,  self::EXPERIENCE_MEDIUM_SLOW => 816525,  self::EXPERIENCE_MEDIUM_FAST => 778688,  self::EXPERIENCE_FAST => 622950, self::EXPERIENCE_ERRATIC => 513934, self::EXPERIENCE_FLUCTUATING => 1214753 ),
		93  => array(self::EXPERIENCE_SLOW => 1005446, self::EXPERIENCE_MEDIUM_SLOW => 844653,  self::EXPERIENCE_MEDIUM_FAST => 804357,  self::EXPERIENCE_FAST => 643485, self::EXPERIENCE_ERRATIC => 526049, self::EXPERIENCE_FLUCTUATING => 1254796 ),
		94  => array(self::EXPERIENCE_SLOW => 1038230, self::EXPERIENCE_MEDIUM_SLOW => 873420,  self::EXPERIENCE_MEDIUM_FAST => 830584,  self::EXPERIENCE_FAST => 664467, self::EXPERIENCE_ERRATIC => 536557, self::EXPERIENCE_FLUCTUATING => 1312322 ),
		95  => array(self::EXPERIENCE_SLOW => 1071718, self::EXPERIENCE_MEDIUM_SLOW => 902835,  self::EXPERIENCE_MEDIUM_FAST => 857375,  self::EXPERIENCE_FAST => 685900, self::EXPERIENCE_ERRATIC => 548720, self::EXPERIENCE_FLUCTUATING => 1354652 ),
		96  => array(self::EXPERIENCE_SLOW => 1105920, self::EXPERIENCE_MEDIUM_SLOW => 932903,  self::EXPERIENCE_MEDIUM_FAST => 884736,  self::EXPERIENCE_FAST => 707788, self::EXPERIENCE_ERRATIC => 560922, self::EXPERIENCE_FLUCTUATING => 1415577 ),
		97  => array(self::EXPERIENCE_SLOW => 1140841, self::EXPERIENCE_MEDIUM_SLOW => 963632,  self::EXPERIENCE_MEDIUM_FAST => 912673,  self::EXPERIENCE_FAST => 730138, self::EXPERIENCE_ERRATIC => 571333, self::EXPERIENCE_FLUCTUATING => 1460276 ),
		98  => array(self::EXPERIENCE_SLOW => 1176490, self::EXPERIENCE_MEDIUM_SLOW => 995030,  self::EXPERIENCE_MEDIUM_FAST => 941192,  self::EXPERIENCE_FAST => 752953, self::EXPERIENCE_ERRATIC => 583539, self::EXPERIENCE_FLUCTUATING => 1524731 ),
		99  => array(self::EXPERIENCE_SLOW => 1212873, self::EXPERIENCE_MEDIUM_SLOW => 1027103, self::EXPERIENCE_MEDIUM_FAST => 970299,  self::EXPERIENCE_FAST => 776239, self::EXPERIENCE_ERRATIC => 591882, self::EXPERIENCE_FLUCTUATING => 1571884 ),
		100 => array(self::EXPERIENCE_SLOW => 1250000, self::EXPERIENCE_MEDIUM_SLOW => 1059860, self::EXPERIENCE_MEDIUM_FAST => 1000000, self::EXPERIENCE_FAST => 800000, self::EXPERIENCE_ERRATIC => 600000, self::EXPERIENCE_FLUCTUATING => 1640000 )
		);
	public static function getSpecies($dexId)
	{
		return self::$pokemon[$dexId]['name'];
	}
	protected static function getExperienceType($dexId)
	{
		return self::$pokemon[$dexId]['experience'];
	}
	public static function getLevel($experience, $dexId)
	{
		$experienceType = self::getExperienceType($dexId);
		$level = 100;
		while ($experience < self::$experienceTable[$level][$experienceType])
		{
			$level--;
		}
		return $level;
	}
}
